/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WormfarmRouteImport } from './routes/wormfarm'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as RanchingRouteImport } from './routes/ranching'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaliatrackerRouteImport } from './routes/paliatracker'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as CatchRouteImport } from './routes/catch'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEntitiesRouteImport } from './routes/admin/entities'
import { Route as AdminEditItemsRouteImport } from './routes/admin/edit-items'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as WikiCategoryCatRouteImport } from './routes/wiki/category.$cat'
import { Route as WikiBundleBundleIdRouteImport } from './routes/wiki/bundle.$bundleId'

const WormfarmRoute = WormfarmRouteImport.update({
  id: '/wormfarm',
  path: '/wormfarm',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const RanchingRoute = RanchingRouteImport.update({
  id: '/ranching',
  path: '/ranching',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaliatrackerRoute = PaliatrackerRouteImport.update({
  id: '/paliatracker',
  path: '/paliatracker',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchRoute = CatchRouteImport.update({
  id: '/catch',
  path: '/catch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntitiesRoute = AdminEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditItemsRoute = AdminEditItemsRouteImport.update({
  id: '/edit-items',
  path: '/edit-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const WikiCategoryCatRoute = WikiCategoryCatRouteImport.update({
  id: '/category/$cat',
  path: '/category/$cat',
  getParentRoute: () => WikiRoute,
} as any)
const WikiBundleBundleIdRoute = WikiBundleBundleIdRouteImport.update({
  id: '/bundle/$bundleId',
  path: '/bundle/$bundleId',
  getParentRoute: () => WikiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catch': typeof CatchRoute
  '/garden': typeof GardenRoute
  '/paliatracker': typeof PaliatrackerRoute
  '/profile': typeof ProfileRoute
  '/ranching': typeof RanchingRoute
  '/trade': typeof TradeRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wormfarm': typeof WormfarmRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/edit-items': typeof AdminEditItemsRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/': typeof AdminIndexRoute
  '/wiki/bundle/$bundleId': typeof WikiBundleBundleIdRoute
  '/wiki/category/$cat': typeof WikiCategoryCatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catch': typeof CatchRoute
  '/garden': typeof GardenRoute
  '/paliatracker': typeof PaliatrackerRoute
  '/profile': typeof ProfileRoute
  '/ranching': typeof RanchingRoute
  '/trade': typeof TradeRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wormfarm': typeof WormfarmRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/edit-items': typeof AdminEditItemsRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin': typeof AdminIndexRoute
  '/wiki/bundle/$bundleId': typeof WikiBundleBundleIdRoute
  '/wiki/category/$cat': typeof WikiCategoryCatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catch': typeof CatchRoute
  '/garden': typeof GardenRoute
  '/paliatracker': typeof PaliatrackerRoute
  '/profile': typeof ProfileRoute
  '/ranching': typeof RanchingRoute
  '/trade': typeof TradeRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wormfarm': typeof WormfarmRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/edit-items': typeof AdminEditItemsRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/': typeof AdminIndexRoute
  '/wiki/bundle/$bundleId': typeof WikiBundleBundleIdRoute
  '/wiki/category/$cat': typeof WikiCategoryCatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catch'
    | '/garden'
    | '/paliatracker'
    | '/profile'
    | '/ranching'
    | '/trade'
    | '/wiki'
    | '/wormfarm'
    | '/admin/categories'
    | '/admin/edit-items'
    | '/admin/entities'
    | '/admin/'
    | '/wiki/bundle/$bundleId'
    | '/wiki/category/$cat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catch'
    | '/garden'
    | '/paliatracker'
    | '/profile'
    | '/ranching'
    | '/trade'
    | '/wiki'
    | '/wormfarm'
    | '/admin/categories'
    | '/admin/edit-items'
    | '/admin/entities'
    | '/admin'
    | '/wiki/bundle/$bundleId'
    | '/wiki/category/$cat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catch'
    | '/garden'
    | '/paliatracker'
    | '/profile'
    | '/ranching'
    | '/trade'
    | '/wiki'
    | '/wormfarm'
    | '/admin/categories'
    | '/admin/edit-items'
    | '/admin/entities'
    | '/admin/'
    | '/wiki/bundle/$bundleId'
    | '/wiki/category/$cat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatchRoute: typeof CatchRoute
  GardenRoute: typeof GardenRoute
  PaliatrackerRoute: typeof PaliatrackerRoute
  ProfileRoute: typeof ProfileRoute
  RanchingRoute: typeof RanchingRoute
  TradeRoute: typeof TradeRoute
  WikiRoute: typeof WikiRouteWithChildren
  WormfarmRoute: typeof WormfarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wormfarm': {
      id: '/wormfarm'
      path: '/wormfarm'
      fullPath: '/wormfarm'
      preLoaderRoute: typeof WormfarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranching': {
      id: '/ranching'
      path: '/ranching'
      fullPath: '/ranching'
      preLoaderRoute: typeof RanchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paliatracker': {
      id: '/paliatracker'
      path: '/paliatracker'
      fullPath: '/paliatracker'
      preLoaderRoute: typeof PaliatrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catch': {
      id: '/catch'
      path: '/catch'
      fullPath: '/catch'
      preLoaderRoute: typeof CatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entities': {
      id: '/admin/entities'
      path: '/entities'
      fullPath: '/admin/entities'
      preLoaderRoute: typeof AdminEntitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit-items': {
      id: '/admin/edit-items'
      path: '/edit-items'
      fullPath: '/admin/edit-items'
      preLoaderRoute: typeof AdminEditItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wiki/category/$cat': {
      id: '/wiki/category/$cat'
      path: '/category/$cat'
      fullPath: '/wiki/category/$cat'
      preLoaderRoute: typeof WikiCategoryCatRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/bundle/$bundleId': {
      id: '/wiki/bundle/$bundleId'
      path: '/bundle/$bundleId'
      fullPath: '/wiki/bundle/$bundleId'
      preLoaderRoute: typeof WikiBundleBundleIdRouteImport
      parentRoute: typeof WikiRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEditItemsRoute: typeof AdminEditItemsRoute
  AdminEntitiesRoute: typeof AdminEntitiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEditItemsRoute: AdminEditItemsRoute,
  AdminEntitiesRoute: AdminEntitiesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WikiRouteChildren {
  WikiBundleBundleIdRoute: typeof WikiBundleBundleIdRoute
  WikiCategoryCatRoute: typeof WikiCategoryCatRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiBundleBundleIdRoute: WikiBundleBundleIdRoute,
  WikiCategoryCatRoute: WikiCategoryCatRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatchRoute: CatchRoute,
  GardenRoute: GardenRoute,
  PaliatrackerRoute: PaliatrackerRoute,
  ProfileRoute: ProfileRoute,
  RanchingRoute: RanchingRoute,
  TradeRoute: TradeRoute,
  WikiRoute: WikiRouteWithChildren,
  WormfarmRoute: WormfarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
