/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WormfarmRouteImport } from './routes/wormfarm'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as RanchingRouteImport } from './routes/ranching'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaliatrackerRouteImport } from './routes/paliatracker'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as CatchRouteImport } from './routes/catch'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WikiCatRouteImport } from './routes/wiki/$cat'
import { Route as ArchiveStickersRouteImport } from './routes/archive/stickers'
import { Route as ArchivePotatopodsRouteImport } from './routes/archive/potatopods'
import { Route as ArchivePlushiesRouteImport } from './routes/archive/plushies'
import { Route as ArchiveFishRouteImport } from './routes/archive/fish'
import { Route as ArchiveBugsRouteImport } from './routes/archive/bugs'
import { Route as ArchiveArtifactsRouteImport } from './routes/archive/artifacts'
import { Route as AdminEditItemsRouteImport } from './routes/admin/edit-items'

const WormfarmRoute = WormfarmRouteImport.update({
  id: '/wormfarm',
  path: '/wormfarm',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const RanchingRoute = RanchingRouteImport.update({
  id: '/ranching',
  path: '/ranching',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaliatrackerRoute = PaliatrackerRouteImport.update({
  id: '/paliatracker',
  path: '/paliatracker',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchRoute = CatchRouteImport.update({
  id: '/catch',
  path: '/catch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WikiCatRoute = WikiCatRouteImport.update({
  id: '/$cat',
  path: '/$cat',
  getParentRoute: () => WikiRoute,
} as any)
const ArchiveStickersRoute = ArchiveStickersRouteImport.update({
  id: '/archive/stickers',
  path: '/archive/stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivePotatopodsRoute = ArchivePotatopodsRouteImport.update({
  id: '/archive/potatopods',
  path: '/archive/potatopods',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivePlushiesRoute = ArchivePlushiesRouteImport.update({
  id: '/archive/plushies',
  path: '/archive/plushies',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveFishRoute = ArchiveFishRouteImport.update({
  id: '/archive/fish',
  path: '/archive/fish',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveBugsRoute = ArchiveBugsRouteImport.update({
  id: '/archive/bugs',
  path: '/archive/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveArtifactsRoute = ArchiveArtifactsRouteImport.update({
  id: '/archive/artifacts',
  path: '/archive/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditItemsRoute = AdminEditItemsRouteImport.update({
  id: '/edit-items',
  path: '/edit-items',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catch': typeof CatchRoute
  '/garden': typeof GardenRoute
  '/paliatracker': typeof PaliatrackerRoute
  '/profile': typeof ProfileRoute
  '/ranching': typeof RanchingRoute
  '/trade': typeof TradeRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wormfarm': typeof WormfarmRoute
  '/admin/edit-items': typeof AdminEditItemsRoute
  '/archive/artifacts': typeof ArchiveArtifactsRoute
  '/archive/bugs': typeof ArchiveBugsRoute
  '/archive/fish': typeof ArchiveFishRoute
  '/archive/plushies': typeof ArchivePlushiesRoute
  '/archive/potatopods': typeof ArchivePotatopodsRoute
  '/archive/stickers': typeof ArchiveStickersRoute
  '/wiki/$cat': typeof WikiCatRoute
  '/admin/': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catch': typeof CatchRoute
  '/garden': typeof GardenRoute
  '/paliatracker': typeof PaliatrackerRoute
  '/profile': typeof ProfileRoute
  '/ranching': typeof RanchingRoute
  '/trade': typeof TradeRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wormfarm': typeof WormfarmRoute
  '/admin/edit-items': typeof AdminEditItemsRoute
  '/archive/artifacts': typeof ArchiveArtifactsRoute
  '/archive/bugs': typeof ArchiveBugsRoute
  '/archive/fish': typeof ArchiveFishRoute
  '/archive/plushies': typeof ArchivePlushiesRoute
  '/archive/potatopods': typeof ArchivePotatopodsRoute
  '/archive/stickers': typeof ArchiveStickersRoute
  '/wiki/$cat': typeof WikiCatRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catch': typeof CatchRoute
  '/garden': typeof GardenRoute
  '/paliatracker': typeof PaliatrackerRoute
  '/profile': typeof ProfileRoute
  '/ranching': typeof RanchingRoute
  '/trade': typeof TradeRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wormfarm': typeof WormfarmRoute
  '/admin/edit-items': typeof AdminEditItemsRoute
  '/archive/artifacts': typeof ArchiveArtifactsRoute
  '/archive/bugs': typeof ArchiveBugsRoute
  '/archive/fish': typeof ArchiveFishRoute
  '/archive/plushies': typeof ArchivePlushiesRoute
  '/archive/potatopods': typeof ArchivePotatopodsRoute
  '/archive/stickers': typeof ArchiveStickersRoute
  '/wiki/$cat': typeof WikiCatRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catch'
    | '/garden'
    | '/paliatracker'
    | '/profile'
    | '/ranching'
    | '/trade'
    | '/wiki'
    | '/wormfarm'
    | '/admin/edit-items'
    | '/archive/artifacts'
    | '/archive/bugs'
    | '/archive/fish'
    | '/archive/plushies'
    | '/archive/potatopods'
    | '/archive/stickers'
    | '/wiki/$cat'
    | '/admin/'
    | '/archive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catch'
    | '/garden'
    | '/paliatracker'
    | '/profile'
    | '/ranching'
    | '/trade'
    | '/wiki'
    | '/wormfarm'
    | '/admin/edit-items'
    | '/archive/artifacts'
    | '/archive/bugs'
    | '/archive/fish'
    | '/archive/plushies'
    | '/archive/potatopods'
    | '/archive/stickers'
    | '/wiki/$cat'
    | '/admin'
    | '/archive'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catch'
    | '/garden'
    | '/paliatracker'
    | '/profile'
    | '/ranching'
    | '/trade'
    | '/wiki'
    | '/wormfarm'
    | '/admin/edit-items'
    | '/archive/artifacts'
    | '/archive/bugs'
    | '/archive/fish'
    | '/archive/plushies'
    | '/archive/potatopods'
    | '/archive/stickers'
    | '/wiki/$cat'
    | '/admin/'
    | '/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatchRoute: typeof CatchRoute
  GardenRoute: typeof GardenRoute
  PaliatrackerRoute: typeof PaliatrackerRoute
  ProfileRoute: typeof ProfileRoute
  RanchingRoute: typeof RanchingRoute
  TradeRoute: typeof TradeRoute
  WikiRoute: typeof WikiRouteWithChildren
  WormfarmRoute: typeof WormfarmRoute
  ArchiveArtifactsRoute: typeof ArchiveArtifactsRoute
  ArchiveBugsRoute: typeof ArchiveBugsRoute
  ArchiveFishRoute: typeof ArchiveFishRoute
  ArchivePlushiesRoute: typeof ArchivePlushiesRoute
  ArchivePotatopodsRoute: typeof ArchivePotatopodsRoute
  ArchiveStickersRoute: typeof ArchiveStickersRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wormfarm': {
      id: '/wormfarm'
      path: '/wormfarm'
      fullPath: '/wormfarm'
      preLoaderRoute: typeof WormfarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranching': {
      id: '/ranching'
      path: '/ranching'
      fullPath: '/ranching'
      preLoaderRoute: typeof RanchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paliatracker': {
      id: '/paliatracker'
      path: '/paliatracker'
      fullPath: '/paliatracker'
      preLoaderRoute: typeof PaliatrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catch': {
      id: '/catch'
      path: '/catch'
      fullPath: '/catch'
      preLoaderRoute: typeof CatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wiki/$cat': {
      id: '/wiki/$cat'
      path: '/$cat'
      fullPath: '/wiki/$cat'
      preLoaderRoute: typeof WikiCatRouteImport
      parentRoute: typeof WikiRoute
    }
    '/archive/stickers': {
      id: '/archive/stickers'
      path: '/archive/stickers'
      fullPath: '/archive/stickers'
      preLoaderRoute: typeof ArchiveStickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/potatopods': {
      id: '/archive/potatopods'
      path: '/archive/potatopods'
      fullPath: '/archive/potatopods'
      preLoaderRoute: typeof ArchivePotatopodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/plushies': {
      id: '/archive/plushies'
      path: '/archive/plushies'
      fullPath: '/archive/plushies'
      preLoaderRoute: typeof ArchivePlushiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/fish': {
      id: '/archive/fish'
      path: '/archive/fish'
      fullPath: '/archive/fish'
      preLoaderRoute: typeof ArchiveFishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/bugs': {
      id: '/archive/bugs'
      path: '/archive/bugs'
      fullPath: '/archive/bugs'
      preLoaderRoute: typeof ArchiveBugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/artifacts': {
      id: '/archive/artifacts'
      path: '/archive/artifacts'
      fullPath: '/archive/artifacts'
      preLoaderRoute: typeof ArchiveArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-items': {
      id: '/admin/edit-items'
      path: '/edit-items'
      fullPath: '/admin/edit-items'
      preLoaderRoute: typeof AdminEditItemsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEditItemsRoute: typeof AdminEditItemsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEditItemsRoute: AdminEditItemsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WikiRouteChildren {
  WikiCatRoute: typeof WikiCatRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiCatRoute: WikiCatRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatchRoute: CatchRoute,
  GardenRoute: GardenRoute,
  PaliatrackerRoute: PaliatrackerRoute,
  ProfileRoute: ProfileRoute,
  RanchingRoute: RanchingRoute,
  TradeRoute: TradeRoute,
  WikiRoute: WikiRouteWithChildren,
  WormfarmRoute: WormfarmRoute,
  ArchiveArtifactsRoute: ArchiveArtifactsRoute,
  ArchiveBugsRoute: ArchiveBugsRoute,
  ArchiveFishRoute: ArchiveFishRoute,
  ArchivePlushiesRoute: ArchivePlushiesRoute,
  ArchivePotatopodsRoute: ArchivePotatopodsRoute,
  ArchiveStickersRoute: ArchiveStickersRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
