const stickerMap = {
  "sticker-farm-badruu": "Carefully Cultivated",
  "sticker-meow-tamala": "Cat's Meow",
  "sticker-naio": "Choices, Choices",
  "sticker-doesnotcompute-einar": "Does Not Compute",
  "sticker-omgloveit-zeki": "Eyyy!",
  "sticker-letsdothis-sifuu": "Fired Up!",
  "sticker-ivegotit-caleri": "Found It!",
  "sticker-bigbrain": "Genius!",
  "sticker-fishing-einar": "Gone Fishing!",
  "sticker-gottarun-sernuk": "Gotta Run!",
  "sticker-proud-ashura": "Great Job!",
  "sticker-groovin-butterball": "Groovin' Out",
  "sticker-howcouldyou-naio": "Heartbroken",
  "sticker-herestome-tamala": "Here's To Me!",
  "sticker-hmm-subira": "Hmm...",
  "sticker-delightful-eshe": "How Delightful!",
  "sticker-howdy-hodari": "Howdy, Partner!",
  "sticker-shhh-caleri": "Hush",
  "sticker-gotcha-zeki": "I've Got It!",
  "sticker-itme-kenyatta": "It Me",
  "sticker-justapinch-reth": "Just A Pinch",
  "sticker-dressedtokill-jel": "Looking Stylish!",
  "sticker-hearteyes-jina": "Love It!",
  "sticker-chopwood-ashura": "Lumberjack",
  "sticker-drooling-muujin": "Mouth-Watering",
  "sticker-myword-eshe": "My Word!",
  "sticker-bugcatch": "Nice Catch!",
  "sticker-ohplease-eshe": "Oh, Please...",
  "sticker-sadandcute-tau": "Puppy Dog Eyes",
  "sticker-eyeroll-hodari": "Seriously?",
  "sticker-smartthinking-caleri": "Smart Thinking",
  "sticker-takeaphoto-tish": "Snap A Photo",
  "sticker-serving-jel": "So Fierce!",
  "sticker-squee-kenli": "Squee!!",
  "sticker-hunting-hassian": "Steady Aim",
  "sticker-tearsofjoy-reth": "Tears Of Joy",
  "sticker-teamwork-sifuu": "That's Teamwork!",
  "sticker-everythingisfine-reth": "This Is Fine",
  "sticker-solame-kenyatta": "What A Drag...",
  "sticker-whatintarnation-hodari": "What In Tarnation?",
  "sticker-mining-hodari": "Workin' The Mines",
  "sticker-yay-tish": "Yay!",
};
export type stickersMapType = typeof stickerMap;

export default stickerMap;
