import type { CROP_Entry } from "~/app/types/GardenTypes";

export const CROPS: CROP_Entry[] = [
  {
    name: "Potato",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Potato.png",
    seedicon:
      "https://palia.wiki.gg/images/thumb/Potato_Seed.png/50px-Potato_Seed.png",
    harvest: "5 Days",
    effect: "Water Retain",
    plotSize: 1,
    basePrice: 0,
    starPrice: 67,
    harvestAmount: 2,
    seed: {
      price: 30,
      input: 1,
      output: 4,
      time: "1h 24m",
    },
    preserve: {
      price: 102,
      time: "54m",
    },
    worm: {
      wormOutput: 4,
      fertilizerOutput: 11,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 6,
      time: "",
    },
  },
  {
    name: "Tomato",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Tomatoe.png",
    seedicon:
      "https://palia.wiki.gg/images/thumb/Tomato_Plant_Seed.png/50px-Tomato_Plant_Seed.png",
    harvest: "4+2+2+2 Days",
    effect: "Water Retain",
    plotSize: 1,
    basePrice: 0,
    starPrice: 34,
    harvestAmount: 8,
    seed: {
      price: 60,
      input: 3,
      output: 2,
      time: "30m",
    },
    preserve: {
      price: 51,
      time: "27m",
    },
    worm: {
      wormOutput: 4,
      fertilizerOutput: 11,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 4,
      time: "",
    },
  },
  {
    name: "Wheat",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Wheat.png",
    seedicon: "https://palia.wiki.gg/images/Wheat_Seed.png",
    harvest: "4 Days",
    effect: "Increase Yield",
    plotSize: 1,
    basePrice: 0,
    starPrice: 49,
    harvestAmount: 2,
    seed: {
      price: 18,
      input: 1,
      output: 4,
      time: "42m",
    },
    preserve: {
      price: 0,
      time: "",
    },
    worm: {
      wormOutput: 5,
      fertilizerOutput: 14,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 5,
      time: "",
    },
  },
  {
    name: "Rice",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Rice.png",
    seedicon: "https://palia.wiki.gg/images/Rice_Seed.png",
    harvest: "3 Days",
    effect: "Increase Yield",
    plotSize: 1,
    basePrice: 0,
    starPrice: 40,
    harvestAmount: 2,
    seed: {
      price: 16,
      input: 1,
      output: 4,
      time: "42m",
    },
    preserve: {
      price: 0,
      time: "",
    },
    worm: {
      wormOutput: 5,
      fertilizerOutput: 12,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 5,
      time: "",
    },
  },
  {
    name: "Cotton",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Cotton.png",
    seedicon: "https://palia.wiki.gg/images/Cotton_Seed.png",
    harvest: "5 Days",
    effect: "Quality Boost",
    plotSize: 1,
    basePrice: 0,
    starPrice: 45,
    harvestAmount: 2,
    seed: {
      price: 20,
      input: 1,
      output: 3,
      time: "36m",
    },
    preserve: {
      price: 42,
      time: "8m",
    },
    worm: {
      wormOutput: 0,
      fertilizerOutput: 0,
      time: "",
    },
    glowworm: {
      wormOutput: 0,
      fertilizerOutput: 0,
      time: "",
    },
  },
  {
    name: "Carrot",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Carrot.png",
    seedicon: "https://palia.wiki.gg/images/Carrot_Seed.png",
    harvest: "3 Days",
    effect: "Weed Block",
    plotSize: 1,
    basePrice: 0,
    starPrice: 34,
    harvestAmount: 2,
    seed: {
      price: 10,
      input: 1,
      output: 4,
      time: "18m",
    },
    preserve: {
      price: 51,
      time: "27m",
    },
    worm: {
      wormOutput: 5,
      fertilizerOutput: 14,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 5,
      time: "",
    },
  },
  {
    name: "Onion",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Onion.png",
    seedicon: "https://palia.wiki.gg/images/Onion_Seed.png",
    harvest: "4 Days",
    effect: "Weed Block",
    plotSize: 1,
    basePrice: 0,
    starPrice: 45,
    harvestAmount: 2,
    seed: {
      price: 15,
      input: 1,
      output: 4,
      time: "24m",
    },
    preserve: {
      price: 67,
      time: "36m",
    },
    worm: {
      wormOutput: 6,
      fertilizerOutput: 6,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 6,
      time: "",
    },
  },
  {
    name: "Blueberry",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Blueberry.png",
    seedicon: "https://palia.wiki.gg/images/Blueberry_Bush_Seed.png",
    harvest: "9+3+3+3 Days",
    effect: "Harvest Boost",
    plotSize: 4,
    basePrice: 0,
    starPrice: 58,
    harvestAmount: 24,
    seed: {
      price: 168,
      input: 4,
      output: 2,
      time: "1h 21m",
    },
    preserve: {
      price: 88,
      time: "47m 15s",
    },
    worm: {
      wormOutput: 6,
      fertilizerOutput: 6,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 3,
      time: "",
    },
  },
  {
    name: "Apple",
    icon: "https://mmo-wiki.com/wp-content/uploads/2023/08/Apple.png",
    seedicon: "https://palia.wiki.gg/images/Apple_Tree_Seed.png",
    harvest: "12+6+6+6 Days",
    effect: "Harvest Boost",
    plotSize: 9,
    basePrice: 0,
    starPrice: 96,
    harvestAmount: 64,
    seed: {
      price: 1050,
      input: 10,
      output: 1,
      time: "2h 22m",
    },
    preserve: {
      price: 144,
      time: "1h 16m",
    },
    worm: {
      wormOutput: 8,
      fertilizerOutput: 8,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 4,
      time: "",
    },
  },
  {
    name: "Corn",
    icon: "https://palia.wiki.gg/images/f/f8/Corn.png",
    seedicon: "https://palia.wiki.gg/images/Corn_Seed.png",
    harvest: "5 Days",
    effect: "Harvest Boost",
    plotSize: 1,
    basePrice: 0,
    starPrice: 60,
    harvestAmount: 2,
    seed: {
      price: 22,
      input: 1,
      output: 4,
      time: "48m",
    },
    preserve: {
      price: 90,
      time: "48m",
    },
    worm: {
      wormOutput: 8,
      fertilizerOutput: 8,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 8,
      time: "",
    },
  },
  {
    name: "Spicy Pepper",
    icon: "https://palia.wiki.gg/images/9/97/Spicy_Pepper.png",
    seedicon: "https://palia.wiki.gg/images/Spicy_Pepper_Seed.png",
    harvest: "6+3+3+3 Days",
    effect: "Quality Boost",
    plotSize: 4,
    basePrice: 0,
    starPrice: 48,
    harvestAmount: 24,
    seed: {
      price: 127,
      input: 4,
      output: 2,
      time: "1h 40m",
    },
    preserve: {
      price: 72,
      time: "38m 30s",
    },
    worm: {
      wormOutput: 7,
      fertilizerOutput: 7,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 7,
      time: "",
    },
  },
  {
    name: "Bok Choi",
    icon: "https://palia.wiki.gg/images/4/40/Bok_Choy.png",
    seedicon: "https://palia.wiki.gg/images/Bok_Choy_Seed.png",
    harvest: "3 Days",
    effect: "Weed Block",
    plotSize: 1,
    basePrice: 0,
    starPrice: 45,
    harvestAmount: 2,
    seed: {
      price: 22,
      input: 1,
      output: 4,
      time: "1h 12m",
    },
    preserve: {
      price: 67,
      time: "36m",
    },
    worm: {
      wormOutput: 6,
      fertilizerOutput: 17,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 6,
      time: "",
    },
  },
  {
    name: "Napa Cabbage",
    icon: "https://palia-garden-planner.vercel.app/_vercel/image?url=/crops/napa-cabbage.webp&w=1536&q=100",
    seedicon: "https://palia.wiki.gg/images/Napa_Cabbage_Seed.png",
    harvest: "6 Days",
    effect: "Water Retain",
    plotSize: 1,
    basePrice: 0,
    starPrice: 60,
    harvestAmount: 2,
    seed: {
      price: 15,
      input: 1,
      output: 6,
      time: "48m",
    },
    preserve: {
      price: 90,
      time: "48m",
    },
    worm: {
      wormOutput: 8,
      fertilizerOutput: 8,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 8,
      time: "",
    },
  },
  {
    name: "Batterfly Beans",
    icon: "https://palia.wiki.gg/images/thumb/Batterfly_Beans.png/65px-Batterfly_Beans.png?d2c593",
    seedicon: "https://palia.wiki.gg/images/Batterfly_Bean_Seeds.png",
    harvest: "6+2+2+2 Days",
    effect: "Harvest Boost",
    plotSize: 4,
    basePrice: 0,
    starPrice: 42,
    harvestAmount: 24,
    seed: {
      price: 135,
      input: 2,
      output: 1,
      time: "1h 25m",
    },
    preserve: {
      price: 61,
      time: "33m",
    },
    worm: {
      wormOutput: 6,
      fertilizerOutput: 6,
      time: "",
    },
    glowworm: {
      wormOutput: 1,
      fertilizerOutput: 6,
      time: "",
    },
  },
  {
    name: "Rockhopper Pumpkin",
    icon: "https://palia.wiki.gg/images/Rockhopper_Pumpkin.png?ad54b7",
    seedicon: "https://palia.wiki.gg/images/Rockhopper_Pumpkin_Seed.png",
    harvest: "9+2+2+2 Days",
    effect: "Quality Boost",
    plotSize: 4,
    basePrice: 0,
    starPrice: 132,
    harvestAmount: 8,
    seed: {
      price: 37,
      input: 1,
      output: 4,
      time: "1h 40m",
    },
    preserve: {
      price: 151,
      time: "31m 30s",
    },
    worm: {
      wormOutput: 15,
      fertilizerOutput: 15,
      time: "",
    },
    glowworm: {
      wormOutput: 3,
      fertilizerOutput: 15,
      time: "",
    },
  },
];
