/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WormfarmRouteImport } from './routes/wormfarm'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as IndexRouteImport } from './routes/index'

const WormfarmRoute = WormfarmRouteImport.update({
  id: '/wormfarm',
  path: '/wormfarm',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/wormfarm': typeof WormfarmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/wormfarm': typeof WormfarmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/wormfarm': typeof WormfarmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/garden' | '/wormfarm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/garden' | '/wormfarm'
  id: '__root__' | '/' | '/garden' | '/wormfarm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GardenRoute: typeof GardenRoute
  WormfarmRoute: typeof WormfarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wormfarm': {
      id: '/wormfarm'
      path: '/wormfarm'
      fullPath: '/wormfarm'
      preLoaderRoute: typeof WormfarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GardenRoute: GardenRoute,
  WormfarmRoute: WormfarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
