name: Deploy Palia Client

on:
  push:
    branches: [main]
    paths:
      - "client/**"
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Build React app
        working-directory: ./client
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "client/dist/*"
          target: "/tmp/palia-deploy-client"
          strip_components: 2 # Removes 'client/dist' from path
          rm: true # Clean target directory first

      - name: Execute deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to deployment location
            cd /var/www/games/client/

            # Remove old backup if exists
            if [ -d "palia_old" ]; then
              sudo rm -rf palia_old
              echo "Removed palia_old"
            fi

            # Rename current to old (if exists)
            if [ -d "palia" ]; then
              sudo mv palia palia_old
              echo "Renamed palia to palia_old"
            fi

            # Move new build from temp location
            sudo mv /tmp/palia-deploy-client dist
            sudo mv dist palia

            # Set proper permissions
            sudo chown -R www-data:www-data palia
            sudo chmod -R 755 palia

            echo "Client deployment complete!"
            ls -la /var/www/games/client/palia/
